 all : ledtest buttontest

 buttontest : libmypera.a awekmt k. awkemtkawe
    akmaweklrmalwekrmawawmelrkmawkl;emrkla;wmerlk;akmaweklrmalwekrmawawmelrkmawkl
awkelmraweklr :awkelmraweklr    
    aweklmrlkawmrlkawmelrkmawlekrmklawemrlkawemrlkmawer
edamklwerm : aweklmrlkawmrlkawmelrkmawlekrmklawemrlkawemrlkmawer
    wlkrmlakwemrklawmrlkamwerklmaweklr
 buttontest : libmypera.a awekmt k. awkemtkawe
    akmaweklrmalwekrmawawmelrkmawkl;emrkla;wmerlk;akmaweklrmalwekrmawawmelrkmawkl
awkelmraweklr :awkelmraweklr    
    aweklmrlkawmrlkawmelrkmawlekrmklawemrlkawemrlkmawer
edamklwerm : aweklmrlkawmrlkawmelrkmawlekrmklawemrlkawemrlkmawer
    wlkrmlakwemrklawmrlkamwerklmaweklr